# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('questions', models.TextField(verbose_name='问题')),
                ('option_one', models.CharField(max_length=50, verbose_name='第一个选项')),
                ('option_two', models.CharField(max_length=50, verbose_name='第二个选项')),
                ('poll_one', models.IntegerField(default=0, verbose_name='第一个票数')),
                ('poll_two', models.IntegerField(default=0, verbose_name='第二个票数')),
            ],
        ),
    ]
