# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=50, verbose_name='用户账号')),
                ('pwd', models.CharField(max_length=50, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': '问题'},
        ),
    ]
